apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-pod-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1